sudo: false
language: node_js
node_js:
- 0.12.7
before_script:
- npm install -g bower grunt-cli
- bower install
addons:
#  sauce_connect:
#    username: bblseco
#    access_key:
#      secure: ORVbeh4LHOQ/HXCoWKkZ9XL0mo62PbC2FO3HXgCR61FY8M735CK9NQCRQzqUva/HIJGzHhGcyvNcJjNxJKD/6VulFGBWwSfQ7z1/dYJl7psJwLBm7Ec5zWpC4cvopLoZXG44XLLoKj7k0eMP4vJ5GAeondrTG7BfTl83jmL52+A=
deploy:
  provider: openshift
  user: pat18.e@gmail.com
  password:
    secure: InrFMc761hbJRS4Hfqpvy0gzaF4YIlkbSuFivWCOlOvyUbV4aYPg9DAxARDYzlRkqND3ov9VlTEGJ5Zo5lfrGX25rOuMp1IH4sBFbPB2DjTxY9KwFMj/xOfKfcWtwsU/ePGX1CLP6pj+mcUrKOpTTg8BNAAbTIGmvoN8zjsJ3JzpJTK2oOwztEabpO7/fLdswfnfCnC9m7vTzftTGsroh8RaZ/AP1bkY5/Sj6cxGNJNPb/XhgALaJbRFBTwCut2K+vreCSV55SX3rgAxYgAUftEew5lCHhwblrWu2u3rORCqfbg3K8cne5IBKkdjK2f+AfFbMQUtI3Icz25xeht2e9ExXS/2PG7uhAmzgt2ssXWiPaWqfKxEbMrUO8XZrGo0/6P+w26ztDa0eQtm7dMUKn26WKYCmIviuGC3BPdHxLCSvGL/eA+3W2PzntreCuTOZFGmmDkIJFjUGxOet7p+d6GmOcULUvH4SlH9WiadbA4L1/I78mb/8pdCYGuTO/fg0FvCNF49KzdpF+CI8L4JoxpfX9zovpGGrSbeFm5S32mU8YJwUEyBXItDBmUvrHVaK0gAFbOhsr30IEyRLJvoOITiHe+LP2wtY854r82kgEYpPxYjjJcjusmZj36vt4N/a0DVYOM5o3zptp8NVjGqAdE7AqUqEJN8l4PjhmdMxbE=
  domain:
    master: pellenberger
  app:
    master: jobdesk
  on:
    repo: pellenberger/job-desk
    
after_success:
- grunt build-prod
- cp server.js dist/
- cp package.json dist/
- cp -r .openshift dist/
- cp manifest.appcache dist/
- cd dist
- git init
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- ls -a
- git status
- git add --all
- git status
- git commit -am "Travis change"
