language: node_js
node_js:
- 0.1
install: npm install
before_install: npm install -g grunt-cli
before_script: bower install
#addons:
#  code_climate:
#    repo_token:
#      secure: Z1Bgklztdj5gNXcKG/ZLhjeu/hwz0Gk0hXwph8i/2l1WGt57gKNv/DPLavip4Ptn1JYgtUmVDVU+ggeB+bbW3eiB69DY8LVrn6h2irPkJf+J1YpcK8dsS2r587nAFz2MJQPJ2BDZ01fJgJFjOowHexYndIe/hknP3FGhf+6rR9U=
#  sauce_connect:
#    username: bblseco
#    access_key:
#      secure: ORVbeh4LHOQ/HXCoWKkZ9XL0mo62PbC2FO3HXgCR61FY8M735CK9NQCRQzqUva/HIJGzHhGcyvNcJjNxJKD/6VulFGBWwSfQ7z1/dYJl7psJwLBm7Ec5zWpC4cvopLoZXG44XLLoKj7k0eMP4vJ5GAeondrTG7BfTl83jmL52+A=
deploy:
  provider: openshift
  skip_cleanup: true
  user: mediamatik@seco.admin.ch
  password:
    secure: lJBStixxDuIDsdrOidjsUxMGcTT+wQMJcJzYHo0NQML3MrOs6dmtfM+GM6snrZxHJ88VMmTSn8xNVUpjqDUJoLLunshqM3fx0imZ6MiYjbxYEvQJy2thDwPKrKgxspeISf0ITBBrB+BnC9c2HYfo1CQrZNvw6V3nTMtzhXsdOdg=
  app: jobdesk
  domain: alvchegov
  on:
    repo: alv-ch/job-desk
after_script:
- cat build/coverage/reports/lcov/lcov.info | codeclimate
