language: node_js
node_js:
- 0.12.7
install: npm install
before_install: npm install -g grunt-cli
before_script: bower install
script: grunt build
addons:
  code_climate:
    repo_token:
      secure: Z1Bgklztdj5gNXcKG/ZLhjeu/hwz0Gk0hXwph8i/2l1WGt57gKNv/DPLavip4Ptn1JYgtUmVDVU+ggeB+bbW3eiB69DY8LVrn6h2irPkJf+J1YpcK8dsS2r587nAFz2MJQPJ2BDZ01fJgJFjOowHexYndIe/hknP3FGhf+6rR9U=
deploy:
  provider: openshift
  user: mediamatik@seco.admin.ch
  password:
    secure: EWtmMwwZN6tLJi7z/8Jhh0g07BAnkK6n02Ugs+3265tDR8rYxd6XM2Yb4YpxruOB8n30qNMCExydoO30d7XNFW7fzhzO+i1H25nD2Cm49yxG6QjwghT19i90/i0+RYSVwV34hy3NhCHOjWdXBMCJhY6Lx+R3xAMJYKP6vP2a3Dlz5FoTS8BjwvVXi00rI8t5lyx6khGkeg6FJSe5LNz4+a19fgW2Q1dtPz8kAHfg+yKDVWPTySGId3SITwZeSc5CmQ61T62JP9MzibJyPMNuaAwi94Lv+uUZ05T9foM6fHcwTsKZ9zQgX63yyHNUh2NMT6zslEue1mK2IFlDyfaembXjGmH/YZ23E9Hg/td/xFHxcvr9z18ZxoU8LXAACdbk+tdux3/WYDybsVyT384mMYlIeroACuqFjenQZ56018t4PlQ9f8ssFziROfm2b4oManf0JfGKX1gnIcJFlVBH4U+c7hLomVxba75ArXREjP/yquODOhpNzaTSeNJuaVxe95O744QqLeV1rGbJUlHsJwggjCU/QPOzQMgjGb0Wu1hf7T10XchkaHJQjhGqwYnAi9QHa2S56kVtkjl9RGvLitAmSPFZS/FOHnjW4oP0zUn7xAV7zCW1mz5MDdl/gGehpEE7T23zu6rTJHh/S6eQjnUWDlWcp7pN3387JHUvgPo=
  app: jobdesk
  domain: alvchegov
  on:
    repo: alv-ch/job-desk
after_script:
- cat build/coverage/reports/lcov/lcov.info | codeclimate
