language: node_js
node_js:
- 0.12.7
install: npm install
before_install: npm install -g grunt-cli
before_script: bower install
script: grunt build
addons:
  code_climate:
    repo_token:
      secure: Z1Bgklztdj5gNXcKG/ZLhjeu/hwz0Gk0hXwph8i/2l1WGt57gKNv/DPLavip4Ptn1JYgtUmVDVU+ggeB+bbW3eiB69DY8LVrn6h2irPkJf+J1YpcK8dsS2r587nAFz2MJQPJ2BDZ01fJgJFjOowHexYndIe/hknP3FGhf+6rR9U=
deploy:
  provider: openshift
  skip_cleanup: true
  user: mediamatik@seco.admin.ch
  password:
    secure: mPqtqPcyFFi4vZ0g1M4KYDJHN4PUlvI9vCWyBSeUtO25bqhVAhaMMsixOdoHUuTroVPPFarkxMkcazlISNTH5ZANJ+YKVsbrQ3wgK3IxtIPZRLGAYvuUZ4iGEwi6ktEvNgjPDyTX8afubwL/spTWDo62dtqTAX7WU1NY2rjfSpApOTnJE0KseoQ9Vh9jw+eJ3OZewkBf4O4R6GzV1pTCHRDPCSIfEzDEBpxgZjqQ+f2wuZI3ipaSRd/glge1DXzs5/a5CqigVRVSkXEsHA3ac08u6lvnYqJlFkt65St6RwyuixxQ6Hdq2tsjtyDelWG406pZQh/KnZGAPZ6j42SptTt1Fr25HBugvZqy9Eb0ehJIVwQNBOaahlbUXGYEUpa+vvZckxM12mHnBGSq+cL7H01lIqqfNGtRPli8+K9a1q1uqOitdyBPRoAtijZx7ozgUxTGEiqj3y8LIyC+4ruUwEeeY66DDs5i1t1qsn2zllJrHR1SojP/lhDKzPDl45+lZM1cxdhfN2Aml2QjSVr+iiykRkCs6g90wolAU2pGp0m+v3umLzGagNIbXsQ0EBH1wuOMJvYxrp/4DV8gjc6laWd7szuFgNFCe4QN4GiToXyYdwKc1STj5WjSB9ekIMlCTFkLieVRjCDkSNzJXaoD0nteuWrlzZZvSj0fRFwNr6M=
  app: jobdeskdev
  domain: alvchegov
  on:
    repo: alv-ch/job-desk
    branch: dev
after_script:
- cat build/coverage/reports/lcov/lcov.info | codeclimate
notifications:
  slack: alv-ch:tf9xRwey0Crj0qdDxljP5lDX
