sudo: false
language: node_js
node_js:
- 0.12.7
before_script:
- npm install -g bower grunt-cli
- bower install
addons:
deploy:
  provider: openshift
  user: pat18.e@gmail.com
  password:
    secure: sWc7LzpcxyiVwvZg7TddPSDoOQdpaLXYy6KKSRdXOMuC4yrOqRoM1jBjcihOqrovh4ts1rfNV/dFkBXEj5M9wQJT7uzsEZQkvt2OCsYm53cW1WmNh0RcCB3K2FBIrLzv656AHGRFc6Ov0bsfzk7CTCVGXRWyjUTkc+hcED4dcFygUE7YN3d4Vb+AyV2hwF2YafEoQZzeC+WjgIloXz1uyKSt6gB5qlos6IlB2kh1yRhKJNq2iF5jzCpcZYLIJjf6xoay2QjAl9bWbvFRx0f9sTngQYjiwXVi/O0MYSTHqCteFdlFrIStJM4Y0lQkvRHteiGfsb62feUcj+ZnVJHTraZDWNN4BRtLiK2/tv7DR9KoN5ISlkC/PRHOwh5ozJLMoBJr60q4c7EOnpUJje/gIBZpXdZWByi08NDle4Z0IsSCgpU+s2j4oLqHBbdYAyohw1Rw62C1hB1ykoiADkgrqhRyfxdSj4ZCpPOm2C+/cisnETqsRFwWLdR3zArUwRK1rq6F8qZmFNl/mIOErasY5KUfzmJqgsa2FVW2BokQE0tV9yTzGfhe+IVVQXZmcAs2Xu++Gd7bVV7wF6iYtR8FjJYkjJBi54jAU/+JVX0OgnRlKr/pw/X4fRSe7FLYN/R4PInKLuUOUBjlObZZAuEgHrVUTcir9KHqY4gV7wxC134=
  app: jobdesk
  domain: pellenberger
  on:
    repo: pellenberger/job-desk
after_success:
- grunt build-prod
- cp server.js dist/
- cp package.json dist/
- cp -r .openshift dist/
- cd dist
- git init
- git config --global user.email "travis@localhost.localdomain"
- git config --global user.name "Travis CI"
- ls -a
- git status
- git add --all
- git status
- git commit -am "Travis change"
